services:
  web:
    build: ./ticketing
    ports:
      - "8081:80" 
    environment:
      DB_ADDRESS: ${DB_ADDRESS}
    depends_on:
      - db 
    develop:
      watch:
        - path: ./ticketing
          target: /var/www/html
          action: sync
        - path: ./ticketing/Dockerfile
          target: /var/www/html/Dockerfile
          action: rebuild
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: lamp_db
    volumes:
      - ./mysql_data:/var/lib/mysql 
      - ./ticketing/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"